Repository agamjotsingh18/trendhora, pull requests merged in 2025-09, with the labels that each got.

#238 Fixed toast text visibilty in dark mode in shop section and added gap between itemCard
  client/src/components/Category/Category.css
  client/src/components/Featured/Items/FeaturedItems.css
  client/src/components/Shop/Container/ShopCategory.css
  client/src/components/Toaster/toaster.css
  server/itemsCollection_cleaned.js
  server/seed.js
Labels: gssoc25, Level2

#260 Feature: Contact Us Page Fix & Implementation
  client/src/app/App.js
  demo.html
Labels: gssoc25, Level1

#267 Chatbot Feature Implementation
  client/src/Context/ChatbotContext.js
  client/src/Context/ChatbotProvider.js
  client/src/app/App.js
  client/src/components/Chatbot/Chatbot.css
  client/src/components/Chatbot/Chatbot.js
  client/src/components/Chatbot/Chatbot.test.js
  client/src/components/Chatbot/ChatbotService.js
  client/src/components/Chatbot/ChatbotUtils.js
  client/src/components/Chatbot/README.md
  client/src/components/Chatbot/index.js
  demo.html
Labels: gssoc25, Level3, Frontend

#273 feat: #269 Complete enterprise UI transformation with Material-UI and them…
  client/package-lock.json
  client/package.json
  client/src/components/Card/RelatedCard/RelatedCard.css
  client/src/components/Card/RelatedCard/RelatedCard.js
  client/src/components/Item/Carousel/ItemCarousel.css
  client/src/components/Item/Carousel/ItemCarousel.js
  client/src/components/Item/Description/Description.css
  client/src/components/Item/Description/Description.js
  client/src/components/Item/Detail/Detail.css
  client/src/components/Item/Detail/Detail.js
  client/src/components/Item/Item.css
  client/src/components/Item/Item.js
  client/src/components/Item/Related/Related.css
  client/src/components/Item/Related/Related.js
  client/src/components/Loader/loader.css
  client/src/components/Loader/loader.js
  server/.env.example
Labels: gssoc25, Level3
