Repository agamjotsingh18/trendhora, pull requests merged in 2025-08, with the labels that each got.

#53 #Fixes 39 [UI] Privacy Policy and Terms & Conditions buttons not functional
  client/src/app/App.js
  client/src/components/Footer/Footer.css
  client/src/components/Footer/Footer.js
  client/src/components/Legal/PrivacyPolicy/PrivacyPolicy.css
  client/src/components/Legal/PrivacyPolicy/PrivacyPolicy.js
  client/src/components/Legal/TermsConditions/TermsConditions.css
  client/src/components/Legal/TermsConditions/TermsConditions.js
Labels: gssoc25, Level1

#55 Added responsive color options in product detail section
  client/src/components/Item/Detail/Detail.css
  client/src/components/Item/Detail/Detail.js
Labels: good first issue, gssoc25, Level1

#45 Solving ISSUE 32 - Backend URL in Frontend .env
  CONTRIBUTING.md
  client/.env.example
  client/.gitignore
  client/src/components/Authentication/Login/Login.js
  client/src/components/Card/Cart/Cart.js
  client/src/components/Card/LoginCard/LoginCard.js
  client/src/components/Card/RegisterCard/RegisterCard.js
  client/src/components/Item/Related/Related.js
  client/src/components/Shop/Shop.js
  client/src/routes/CategoryView.jsx
  client/src/routes/Home.jsx
  client/src/routes/ItemView.jsx
  server/.env.example
  server/models/User.js
  server/package-lock.json
Labels: good first issue, gssoc25, Level1

#94 SECURITY.md
  SECURITY.md
Labels: gssoc25, Level1

#135 removed issue of header overlapping the pages of the footer
  client/src/Pages/Footer/Accessibility/Accessibility.css
  client/src/Pages/Footer/Accessibility/Accessibility.js
  client/src/Pages/Footer/Faq/FaqList.js
  client/src/Pages/Footer/Refund/Refund.js
  client/src/Pages/Footer/Shipping/Shipping.js
Labels: gssoc25, Level1

#142 user have to login before wishlisting
  client/src/components/Card/ItemCard/ItemCard.js
  server/controllers/itemsController.js
  server/utility/asyncHandler.js
Labels: gssoc25, Level3

#153 added role to schema and added auth middleware
  server/controllers/authController.js
  server/middlewares/verifyjwt.js
  server/models/User.js
Labels: gssoc25, Level2

#192 Added Contact Us Page
  client/src/app/App.js
  client/src/components/Footer/Footer.js
  client/src/components/Nav/DrawerNav/DrawerNav.js
  client/src/components/Nav/Nav-Links/NavLinks.js
  client/src/routes/ContactUs.css
  client/src/routes/ContactUs.js
Labels: gssoc25, Level3

#203 UI Enhancement for main Page
  client/src/app/App.css
  client/src/app/App.test.js
  client/src/components/Footer/Footer.css
  client/src/components/Footer/Footer.js
  client/src/components/Footer/Footer.test.js
  client/src/components/Header/Header.css
  client/src/components/Landing/Landing.css
  client/src/components/Landing/Landing.js
  client/src/components/Landing/Landing.test.js
  client/src/components/Loader/loader.css
  client/src/components/Nav/Controls/Control.css
  client/src/components/ThemeToggle/ThemeToggle.css
  client/src/components/ThemeToggle/ThemeToggle.test.js
  client/src/components/UIEnhancements.test.js
  client/src/components/Wishlist/index.css
Labels: gssoc25, Level3
